spring.application.name=springkafka
spring.kafka.bootstrap-servers=localhost:9092


spring.security.oauth2.client.registration.google.client-id=32385793151-7rqgq0o6a1flf00tttpgpq1e5cv0r05f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

